# Generated by Django 5.2.11 on 2026-02-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
    ]
